### ISSUE TITLE
Planting Limitation

### ISSUE THREAD

**Issue by ghost** [DemmyDemon/esx_uteknark#2] opened 2019-11-12 04:48 UTC
This is a great work, and using it right now for my server, However it causing some delay to due unlimited numbers of planting. My server is high populated right now and every single of them are planting. Would love it to be implemented.

**Comment by DemmyDemon** [comment] 2019-11-19 13:38
"causing some delay" - Can you give more information on this?
It is too vague for me to reproduce, though I've tried all kinds of tests to see what could be slowing down.

Please give me more information on the delays it's causing.
Also, what kind of limitation would you like to see? Only a specific number of plants within drawing distance, or what is the problem?

I can't do anything without your help.

**Comment by ghost** [comment] 2019-11-19 14:32
I turned IT off and the Database delay were gone. Maybe because theres too much plants planted. What i mean is for Plant LImitation is players can no longer plant if they have planted 5 plants or 10 plants already something like that. :)

**Comment by DemmyDemon** [comment] 2019-11-19 17:13
The script does not know who planted the plants. 5 plants is hardly worth anyone's time.

What kind of "Database delay" do you mean?

I've tested this with _tens of thousands_ of plants, and it didn't really cause any database issues. You will have to be more specific.

**Comment by DemmyDemon** [comment] 2019-12-19 13:25
No specific information seems to be forthcoming. Closing.
Please open a new issue with specific data for consideration. Thank you.

**Closed as completed by DemmyDemon** 2019-12-19 13:25 UTC
