### ISSUE TITLE
Item unusable on ESX Legacy

### ISSUE THREAD

**Issue by aminextv989** [DemmyDemon/esx_uteknark#32] opened 2022-07-18 15:04 UTC
I have that Issue that i cant plant a weedseed.
He say me item unusable.

**Comment by DemmyDemon** [comment] 2022-07-18 19:58
Please provide a server log.

**Comment by aminextv989** [comment] 2022-07-18 20:08
I have ESX Legacy, FXServer 5714 Gamebuild 2612.

[ citizen-server-impl] Started resource esx_uteknark
[ script:esx_uteknark] [22:02:05] <esx_uteknark> Product item in configuration (weedbaggy) found in ESX: Good!
[ script:esx_uteknark] [22:02:05] <esx_uteknark> Seed item in configuration (weedseed) found in ESX: Good!
[ script:esx_uteknark] [22:02:06] <esx_uteknark> Uteknark loaded 0 plants

He dont give me a error.

He say me ingame that i cant use this item weedseed.

**Comment by DemmyDemon** [comment] 2022-07-19 05:05
Okay, and what does the client log say, then?

**Comment by aminextv989** [comment] 2022-07-19 07:58
The Client Log is empty.

This make the Items useable ESX.RegisterUsableItem(Config.Items.Seed, function(source)

It is not working for me. I cant use the item but i dont have any errors.

**Comment by DemmyDemon** [comment] 2022-07-19 08:09
Okay, then I have to _guess_ what the problem is. That's not going to work.
As for the client log being empty, I simply don't believe you. I have never experienced the FiveM client not logging a single line to it's log file.

Maybe you mean you couldn't find any relevant lines? If so, then please just drop the whole file in here so I can have a look for myself.

**Comment by aminextv989** [comment] 2022-07-19 14:36
I can give you a youtube link.
I have make a livestream and test it there.
The stream is german, but you can see, i try to use the weed_seed from inventory.
On the left side at the bottom he say: Dieser gegenstand ist nicht benutztbar. The Item is unusable.
I think it is while i use ESX Legacy this is 1.2 i mean.

**Comment by DemmyDemon** [comment] 2022-07-19 14:39
I know that is the message you are seeing on your screen.
What I could look at is the client log.
If you don't want to give me a client log, then I have to guess what the problem is, and my guess is that you have two items with similar display names, and you are mixing them up.

For any further guesses, I have to see a client log.

Also, keep in mind that this is an unmaintained plugin that hasn't even been touched in a year and a half. It might very well be completely broken. There are several forks, so maybe one of them is still active?
I'm trying to help you, but you are not giving me the information I need, so unless you do that I will simply close the issue.

**Comment by aminextv989** [comment] 2022-07-19 14:42
How can i give you the client log???
Than i will do this.

**Comment by DemmyDemon** [comment] 2022-07-19 14:51
Client logs should be somewhere under `%localappdata%/FiveM`
It's been a long time since I even had it installed, so I can't open and check on my own computer.

**Comment by aminextv989** [comment] 2022-07-19 16:05
I have actually issues with my Inventory, when i have fix it, i make you a log.

**Comment by DemmyDemon** [comment] 2022-07-21 13:27
Since I haven't heard back, I'll assume the problem wasn't with esx_uteknark and close this.

**Closed as completed by DemmyDemon** 2022-07-21 13:27 UTC
